module RBS
  class TypeName
    type kind = :class | :alias | :interface

    attr_reader namespace: Namespace

    attr_reader name: Symbol

    attr_reader kind: kind

    def initialize: (namespace: Namespace, name: Symbol) -> void

    def ==: (untyped other) -> bool

    def hash: () -> Integer

    def to_s: () -> ::String

    def to_json: (*untyped a) -> untyped

    def to_namespace: () -> Namespace

    def class?: () -> bool

    def alias?: () -> bool

    def absolute!: () -> TypeName

    def absolute?: () -> bool

    def relative!: () -> TypeName

    def interface?: () -> bool

    def with_prefix: (Namespace namespace) -> TypeName
  end
end
